name: Vietnamvpn Auto Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4

      - name: Cài đặt Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build và Đóng gói đầy đủ
        run: |
          go mod tidy
          go build -o XrayR -trimpath -ldflags "-s -w" main.go
          
          # Tải thêm 2 file dữ liệu địa lý cần thiết
          curl -L https://github.com/v2fly/geoip/releases/latest/download/geoip.dat -o geoip.dat
          curl -L https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat -o geosite.dat
          
          # Nén tất cả vào file zip (đặt tên đúng XrayR-linux.zip cho khớp install.sh của bác)
          zip XrayR-linux.zip XrayR geoip.dat geosite.dat

      - name: Đẩy hàng lên Release
        uses: softprops/action-gh-release@v2
        with:
          files: XrayR-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
